name: Continuous Delivery workflow

permissions:
  contents: read
  pull-requests: write

on: 
  push:
    branches:  
      - main 

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      
      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
            **.py
            README.md
  
  deploy:
    needs: deliver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: projetozipado.zip

      - name: Display structure of downloaded files
        run: ls -R