name: Continuous Delivery workflow

permissions:
  contents: read
  pull-requests: write

on: 
  push:
    branches:  
      - main 

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      
      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: |
            **.py
            README.md
  
  deploy:
    needs: deliver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: projetozipado

      - name: Display structure of downloaded files
        run: ls -R

    docker:
      needs: deliver
      runs-on: ubuntu-latest
      steps:
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v4
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v4
        -
          name: Login to Docker Hub
          uses: docker/login-action@v4
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
            name: Build and push
            uses: docker/build-push-action@v7
            with:
              push: false
              tags: user/app:latest